services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=POSTGRE_DB
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=POSTGRES_USER
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

